### ISSUE TITLE
No matching distribution found for flexsea

### ISSUE THREAD

**Issue by mkshah909** [DephyInc/Actuator-Package#62]
I am running Ubuntu Desktop 20.10 on a Raspberry Pi 4 8GB.
Python version version 3.8.6
pip version 20.1.1

I am able to pip install other packages like numpy, matplotlib, virtualenv, opencv-python etc.

However, when I try `pip install flexsea`, I get the following errors:
```
ERROR: Could not find a version that satisfies the requirement flexsea (from versions: none)
ERROR: No matching distribution found for flexsea
```

Any ideas? Am I missing something basic to get the package installed? Is there a known workaround?

Thanks!

**Comment by Sotilrac** [comment]
We've been able to use this on Raspbian, but never tested it on Ubuntu on a Pi. Is your Ubuntu 64bit?

**Comment by mkshah909** [comment]
Yes, it is 64bit Ubuntu, will share `uname -a` outputs promptly.

**Comment by Sotilrac** [comment]
@mkshah909 Also, what is your python version? make sure you install the 3.7.x

**Comment by mkshah909** [comment]
Output from `uname -a`:
`Linux pi-desktop 5.8.0-1006-raspi #9-Ubuntu SMP PREEMPT Fri Oct 16 12:55:30 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux`

Trying to install python 3.7.x either concurrently or to replace 3.8.6 (currently installed) and trying again.
Thanks!

**Comment by mkshah909** [comment]
Update:

Installing a separate python 3.7.9 with pyenv and installing flexsea with pip into a virtual environment running that version of python worked on my PC (Ubuntu 20.04 64bit). I was able to run `run_demos.py` (which seems to have replaced `fxMain.py`) in `read_only` mode as a test.

However, following an identical setup procedure (pyenv, python version 3.7.9, successful `pip install flexsea` in virtual environment) on my raspberry pi, the demos fail when trying to initialize an instance of FlexSEA `fx = flex.FlexSEA()` with the following error message:

```Running Experiment [0] with [1] connected device.
Using ports:	['/dev/ttyACM0']
Using baud rate:	230400
loading... /home/pi/.pyenv/versions/3.7.9/envs/flexsea_env/lib/python3.7/site-packages/flexsea/libs/linux/libfx_plan_stack.so
Problem loading the library
 /home/pi/.pyenv/versions/3.7.9/envs/flexsea_env/lib/python3.7/site-packages/flexsea/libs/linux/libfx_plan_stack.so: cannot open shared object file: No such file or directory

Problem encountered when running the demo: /home/pi/.pyenv/versions/3.7.9/envs/flexsea_env/lib/python3.7/site-packages/flexsea/libs/linux/libfx_plan_stack.so: cannot open shared object file: No such file or directory
/home/pi/.pyenv/versions/3.7.9/envs/flexsea_env/lib/python3.7/site-packages/flexsea/libs/linux/libfx_plan_stack.so: cannot open shared object file: No such file or directory
Exception ignored in: <function FlexSEA.__del__ at 0xffff93907f80>
Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/flexsea_env/lib/python3.7/site-packages/flexsea/flexsea.py", line 32, in __del__
    self.close_all()
  File "/home/pi/.pyenv/versions/flexsea_env/lib/python3.7/site-packages/flexsea/flexsea.py", line 181, in close_all
    self.c_lib.fxCloseAll()
AttributeError: 'NoneType' object has no attribute 'fxCloseAll'```

It seems like it is unable to find the `libfx_plan_stack.so' shared library, even though I can see the .so file when I enter `ls -l /home/pi/.pyenv/versions/3.7.9/envs/flexsea_env/lib/python3.7/site-packages/flexsea/libs/linux/` with output:
```-rw-rw-r-- 1 pi pi 2709376 Mar 18 18:37 libfx_plan_stack.so
-rw-rw-r-- 1 pi pi 2785274 Mar 18 18:37 libfx_plan_stack_static.a
-rw-rw-r-- 1 pi pi     290 Mar 18 18:37 libs_git_rev_file.h
-rw-rw-r-- 1 pi pi     221 Mar 18 18:37 libs_rev.info```

Any ideas? Thank you so much!

**Comment by Sotilrac** [comment]
Sorry for the late reply. We are working on supporting python 3.9 so you don't need to support different versions of Python.

If you have a link to the Ubuntu image you are using, I could run it on my pi and update the libs accordingly. It seems it's a with how the libs get compiled/are loaded.

**Comment by mkshah909** [comment]
Good to know!

As for the Ubuntu image, I just followed the instructions here: https://ubuntu.com/tutorials/how-to-install-ubuntu-desktop-on-raspberry-pi-4#1-overview

From the Imager software, I chose Ubuntu Desktop 20.10 64-bit for Raspberry Pi.
Also tested it on Ubuntu Server 20.04 LTS 64-bit Raspberry Pi , which has the same results as above.

Thanks a lot!

**Comment by Sotilrac** [comment]
Hello @mkshah909,

We just pushed some updates to this repo and updated the pip package with better support for pi64.

I haven't been able to test it on your image yet. If you could please take a look and let us know if the problem persists, it would be great.

**Comment by mkshah909** [comment]
Hi @Sotilrac 
This is great, thank you so much for pushing the update! I will test it latest by early next week and revert back on this thread.
